# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_to', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=255, null=True)),
                ('email_from', models.EmailField(max_length=254)),
                ('email_body', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('my_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_email.MyEmail')),
            ],
        ),
        migrations.AddField(
            model_name='copy',
            name='my_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_email.MyEmail'),
        ),
    ]
