# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='my_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='my_email',
            new_name='email',
        ),
    ]
