# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='copy_to',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='email_to',
            new_name='email_address',
        ),
        migrations.AlterField(
            model_name='myemail',
            name='copies',
            field=models.ManyToManyField(null=True, to='push_email.Copy'),
        ),
    ]
