# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_email', '0002_auto_20160111_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myemail',
            name='copies',
            field=models.ManyToManyField(to='push_email.Copy'),
        ),
    ]
