# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_email', '0003_auto_20160111_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.TextField()),
            ],
        ),
    ]
